version: "3.8"

services:
  fastapi:
    build: .
    container_name: server
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./db.sqlite:/app/db.sqlite
    environment:
      - DATABASE_URL=sqlite:///./app/db.sqlite
    restart: unless-stopped
